Run the zypp-plugin tests
The tests need rubygem ruby-dbus
but we're not adding a build time dependency in the RPM spec file,
instead putting it to the Docker images used in Travis

diff --git a/zypp-plugin/testsuite/test1 b/zypp-plugin/testsuite/test1
--- a/zypp-plugin/testsuite/test1
+++ b/zypp-plugin/testsuite/test1
@@ -51,6 +51,12 @@ test_pre_del() {
 }
 
 setup() {
+    MOCKDEP=(ruby -rdbus -e 1)
+    if ! "${MOCKDEP[@]}"; then
+        echo "Mock snapperd cannot be run, skipping test"
+        echo "('${MOCKDEP[@]}' failed)"
+        exit 77
+    fi
     $MYDIR/mock-snapperd &
     sleep 1
     PID=$!
